ctitle: Kalyan Pothineni
logo: /docs/img/KalyanPothineni.png
description:
  <p align="left">
  Data Science Graduate Student
  <br><br>
  <em>Seasoned Data Architect with expertise in Data Engineering, Data Management, and Analytics. Mastering Snowflake, AWS, and more. 4X Snowflake, 8X Microsoft Cert.</em>
  <br><br>
  </p>
theme: jekyll-theme-minimal
